worker_processes auto;
events {}
stream {
    upstream mi_app_binaria {
        # '127.0.0.1' es el mismo contenedor. 
        # El puerto 80 debe ser el que use tu archivo /server
        server 127.0.0.1:80; 
    }
    server {
        listen 8080; # El puerto que Cloud Run exige
        proxy_pass mi_app_binaria;
    }
}
